# Generated by Django 5.0.2 on 2024-02-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
